// Swing Engine Version 2 Source Code 
// Copyright (c) 2007-2017

#include "SEVRayRTDevicePCH.h"
#include "SEVRayRTDeviceResource.h"

using namespace Swing;

//----------------------------------------------------------------------------
SEVRayRTImageHandle::SEVRayRTImageHandle()
	:
	mImage(nullptr)
{
}
//----------------------------------------------------------------------------
SEVRayRTImageHandle::~SEVRayRTImageHandle()
{
}
//----------------------------------------------------------------------------
SEVRayRTBitmapHandle::SEVRayRTBitmapHandle()
    :
    mBitmap(nullptr)
{
}
//----------------------------------------------------------------------------
SEVRayRTBitmapHandle::~SEVRayRTBitmapHandle()
{
}
//----------------------------------------------------------------------------
SEVRayRTDeviceCameraHandle::SEVRayRTDeviceCameraHandle()
    :
    mRenderView(nullptr)
{
}
//----------------------------------------------------------------------------
SEVRayRTDeviceCameraHandle::~SEVRayRTDeviceCameraHandle()
{
}
//----------------------------------------------------------------------------
SEVRayRTDeviceLightRectangleHandle::SEVRayRTDeviceLightRectangleHandle()
    :
    mLightRectangle(nullptr)
{
}
//----------------------------------------------------------------------------
SEVRayRTDeviceLightRectangleHandle::~SEVRayRTDeviceLightRectangleHandle()
{
}
//----------------------------------------------------------------------------
SEVRayRTDeviceSkyLightHandle::SEVRayRTDeviceSkyLightHandle()
    :
    mLightDome(nullptr)
{
}
//----------------------------------------------------------------------------
SEVRayRTDeviceSkyLightHandle::~SEVRayRTDeviceSkyLightHandle()
{
}
//----------------------------------------------------------------------------
SEVRayRTDeviceStaticMeshHandle::SEVRayRTDeviceStaticMeshHandle()
    :
    mStaticMesh(nullptr)
{
}
//----------------------------------------------------------------------------
SEVRayRTDeviceStaticMeshHandle::~SEVRayRTDeviceStaticMeshHandle()
{
}
//----------------------------------------------------------------------------
SEVRayRTDeviceSceneNodeHandle::SEVRayRTDeviceSceneNodeHandle()
    :
    mNode(nullptr)
{
}
//----------------------------------------------------------------------------
SEVRayRTDeviceSceneNodeHandle::~SEVRayRTDeviceSceneNodeHandle()
{
}
//----------------------------------------------------------------------------
SEVRayRTDeviceMaterialHandle::SEVRayRTDeviceMaterialHandle()
    :
    mBRDF(nullptr),
    mMaterial(nullptr)
{
}
//----------------------------------------------------------------------------
SEVRayRTDeviceMaterialHandle::~SEVRayRTDeviceMaterialHandle()
{
}
//----------------------------------------------------------------------------
SEVRayRTDeviceBakeViewHandle::SEVRayRTDeviceBakeViewHandle()
    :
    mBakeView(nullptr),
    mUVWGenChannel(nullptr)
{
}
//----------------------------------------------------------------------------
SEVRayRTDeviceBakeViewHandle::~SEVRayRTDeviceBakeViewHandle()
{
}
//----------------------------------------------------------------------------
SEVRayRTDeviceRenderElementHandle::SEVRayRTDeviceRenderElementHandle()
    :
    mRenderElement(nullptr)
{
}
//----------------------------------------------------------------------------
SEVRayRTDeviceRenderElementHandle::~SEVRayRTDeviceRenderElementHandle()
{
}
//----------------------------------------------------------------------------