#ifndef _ERROR_CODES_H_
#define _ERROR_CODES_H_

namespace VRay {
	enum ErrorCode {
		INSTANTIATION_ERROR = -1,
		SUCCESS = 0,

		FILE_OPEN_ERROR,
		FILE_READ_ERROR,
		FILE_FORMAT_ERROR,
		NO_MEMORY_ERROR,
		NOT_SUPPORTED_ERROR,
		LIBRARY_ERROR,
		FILE_WRITE_ERROR,

		FILE_NOT_FOUND_ERROR,
		LOADING_SOME_PLUGINS_ERROR,
		PARSING_VRSCENE_FILE_ERROR,
		SYSTEM_ERROR,
		DR_INIT_ERROR,
		INVALID_RENDER_MODE_ERROR,
		CANNOT_EXECUTE_WHILE_RENDERING_ERROR,
		CANNOT_EXECUTE_WHILE_NOT_RENDERING_ERROR,
		TIMEOUT_ERROR,
		SETTING_PROPERTY_VALUE_ERROR,
		INVALID_PROPERTY_NAME_ERROR,
		INVALID_PLUGIN_CLASS_NAME_ERROR,
		INVALID_PLUGIN_NAME_ERROR,
		INVALID_PLUGIN_ID_ERROR,
		PLUGIN_NAME_ALREADY_EXISTS_ERROR,
		VALUE_OUT_OF_RANGE_ERROR,
		CANNOT_CREATE_RENDER_THREAD_ERROR,
		INTERNAL_ERROR,

		PROXY_CREATION_ERROR,
		INVALID_POINTER_ERROR,
		GI_MAP_EMPTY_ERROR,

		CANNOT_EXECUTE_WHILE_PREPARING_RENDERER_ERROR,
		
		CANNOT_LOAD_RTCUDA_LIBRARY_ERROR,
		CANNOT_LOAD_RTOPENCL_LIBRARY_ERROR,

		NUMBER_OF_ERRORS
	};
}

#endif
